- name: Enable idm:DL1 module
  ansible.builtin.command: dnf module enable idm:DL1 -y
  register: enable_result
  changed_when: "'enabled' in enable_result.stdout"

- name: Run dnf distro-sync
  ansible.builtin.dnf:
    name: '*'
    state: latest
    update_cache: yes

- name: Install idm:DL1/dns module
  ansible.builtin.dnf:
    name: '@idm:DL1/dns'
    state: present

- name: Install IPA server with DNS
  ansible.builtin.command: >
    ipa-server-install
    --realm {{ domain_name | upper }}
    --ds-password {{ idm_password | quote }}
    --admin-password {{ idm_password | quote }}
    --unattended
    --setup-dns
    --auto-forwarders
    --auto-reverse
  register: ipa_install
  failed_when: ipa_install.rc != 0
