- name: Enable idm:DL1 module
  command: dnf module enable idm:DL1 -y
  register: enable_result
  changed_when: "'enabled' in enable_result.stdout"

- name: Run dnf distro-sync
  dnf:
    name: '*'
    state: latest
    update_cache: yes

- name: Install idm:DL1/dns module
  dnf:
    name: '@idm:DL1/dns'
    state: present

- name: Check if IPA is already configured
  command: ipactl status
  register: ipa_status
  ignore_errors: true
  changed_when: false
  check_mode: false

- name: Install IPA server with DNS
  command: >
    umask 0022 && ipa-server-install
    --realm {{ domain_name | upper }}
    --ds-password {{ idm_password | quote }}
    --admin-password {{ idm_password | quote }}
    --unattended
    --setup-dns
    --auto-forwarders
    --auto-reverse
  when: ipa_status.rc == 3 and "'IPA is not configured' in ipa_status.stderr"
  register: ipa_install
  failed_when: ipa_install.rc != 0
  no_log: true