- name: Ensure firewalld is installed
  ansible.builtin.dnf:
    name: firewalld
    state: present

- name: Ensure firewalld is enabled and started
  ansible.builtin.systemd:
    name: firewalld
    enabled: yes
    state: started

- name: Add permanent firewall services for IdM
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  loop: "{{ idm_firewall_services }}"

- name: Reload firewalld to apply permanent changes
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded