- name: Ensure chrony is installed
  ansible.builtin.dnf:
    name: 
    - chrony
    - rhel-system-roles
    state: present

- name: Configure chrony 
  ansible.builtin.copy:
    src: chrony.conf
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: '0644'
  tags: idm_ntp
  notify: Restart chronyd