---
# Change mountpoint from /home to /var/lib/libvirt/images
- name: Check if fstab needs updating
  ansible.builtin.command: grep -q '/home' /etc/fstab
  register: fstab_needs_update
  failed_when: false
  changed_when: false

- name: Update fstab to change mountpoint from /home to /var/lib/libvirt/images
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '\/home'
    replace: '/var/lib/libvirt/images'
  when: fstab_needs_update.rc == 0
  notify: Reload systemd daemon

- name: Unmount /home directory
  ansible.builtin.command: umount /home
  ignore_errors: yes

- name: Create /var/lib/libvirt/images directory
  ansible.builtin.file:
    path: /var/lib/libvirt/images
    state: directory
    mode: '0755'

- name: Mount all filesystems from fstab if needed
  ansible.builtin.command: mount -a
  notify: Verify mounted

- name: Set ACL for root user on /var/lib/libvirt/images
  ansible.posix.acl:
    path: /var/lib/libvirt/images
    entity: root
    etype: user
    permissions: rwx
    state: present