---
# Install libvirt, KVM, and kcli
- name: Install libvirt and KVM packages
  ansible.builtin.dnf:
    name: "{{ libvirt_packages }}"
    state: present

- name: Ensure required groups exist
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop: "{{ libvirt_groups }}"

- name: Add root user to qemu and libvirt groups
  ansible.builtin.user:
    name: root
    groups: "{{ libvirt_groups }}"
    append: yes

- name: Reset connection to ensure new group membership is applied
  ansible.builtin.meta: reset_connection

- name: Enable and start libvirtd service
  ansible.builtin.systemd:
    name: libvirtd
    enabled: yes
    state: started

- name: Enable karmab/kcli COPR repository
  ansible.builtin.command: dnf -y copr enable karmab/kcli
  args:
    creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:karmab:kcli.repo

- name: Install kcli package
  ansible.builtin.dnf:
    name: kcli
    state: present