- name: Install chrony package
  ansible.builtin.package:
    name: chrony
    state: present
  tags: kcli_ntp

- name: Copy chrony.conf file
  ansible.builtin.copy:
    src: chrony.conf
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: '0644'
  tags: kcli_ntp
  notify: Restart chrony service