- name: Install IPA client packages
  ansible.builtin.dnf:
    name: "{{ ipa_client_packages }}"
    state: present
    update_cache: yes

- name: Deploy iparc environment file from template
  ansible.builtin.template:
    src: iparc.j2
    dest: /home/stack/iparc
    owner: stack
    group: stack
    mode: '0644'

- name: Run undercloud IPA installation playbook
  ansible.builtin.command: >
    source ~/iparc && ansible-playbook
    --ssh-extra-args "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    /usr/share/ansible/tripleo-playbooks/undercloud-ipa-install.yaml
  become: yes
  become_user: stack
  args:
    chdir: /home/stack
    executable: /bin/bash
  register: ipa_install_result
  failed_when: ipa_install_result.rc != 0
  no_log: true

- name: Create TLS parameters file
  ansible.builtin.template:
    src: tls-parameters.yaml.j2
    dest: /home/stack/central/tls-parameters.yaml
    owner: stack
    group: stack
    mode: '0644'