- name: Create stack user
  ansible.builtin.user:
    name: stack
    state: present
    password: "{{ stack_password | password_hash('sha512') }}"

- name: Configure sudoers for stack user
  ansible.builtin.copy:
    content: "stack ALL=(root) NOPASSWD:ALL\n"
    dest: /etc/sudoers.d/stack
    mode: '0440'

- name: Create required directories for stack user
  ansible.builtin.file:
    path: "/home/stack/{{ item }}"
    state: directory
    owner: stack
    group: stack
    mode: '0755'
  loop: "{{ stack_directories }}"
