- name: Run undercloud installation with real-time output
  ansible.builtin.command: openstack undercloud install
  become: yes
  become_user: stack
  args:
    chdir: /home/stack
    executable: /bin/bash
  register: result
  failed_when: result.rc != 0