- name: Configure on physical hardware
  gather_facts: true
  hosts: physical_hardware
  roles:
    - kcli
    - virt_bridge
    - vm_provision
  tags: preconfig

- name: Wait 2 minutes before configuring IDM
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  tasks:
    - name: Pause for 2 minutes to allow VMs to stabilize
      ansible.builtin.pause:
        minutes: 2

- name: Configure idm VM
  remote_user: root
  gather_facts: false
  hosts: idms
  roles:
    - idm
  tags: idm

- name: Configure director VM
  become: yes
  become_user: root
  remote_user: root
  gather_facts: false
  hosts: undercloud
  roles:
    - director
  tags: director

- name: Configure director VM 
  gather_facts: false
  remote_user: stack 
  hosts: directors
  roles:
    - rhosp_provision
  tags: rhosp