- name: Check if kcli plans already exist
  ansible.builtin.shell: kcli list plan -o name
  register: plan_check
  changed_when: false
  failed_when: false

- name: Deploy VM plans
  when: "item not in plan_check.stdout_lines"
  block:
    - name: Render {{ item }} plan
      ansible.builtin.template:
        src: "plan-{{ item }}.yml.j2"
        dest: "/root/{{ item }}.yml"
        mode: '0600'

    - name: Create {{ item }} plan
      ansible.builtin.command: "kcli create plan -f /root/{{ item }}.yml {{ item }}"
      no_log: true

  loop:
    - director
    - idm
    - controllers
    - compute

- name: Start VMs and update /etc/hosts
  include_tasks: start_vms.yml
  loop:
    - director
    - idm
  loop_control:
    loop_var: vm_name