- name: Check if kcli plans already exist
  shell: kcli list plan -o json | jq -r '.[]'
  register: plan_check
  changed_when: false
  failed_when: false

- name: Deploy director VM plan
  when: "'director-plan' not in plan_check.stdout_lines"
  block:
    - name: Render director plan
      template:
        src: plan-director.yml.j2
        dest: /root/director-plan.yml
        mode: '0600'
    - name: Create director plan
      command: kcli create plan -f /root/director-plan.yml director-plan
      no_log: true

- name: Deploy idm VM plan
  when: "'idm-plan' not in plan_check.stdout_lines"
  block:
    - name: Render idm plan
      template:
        src: plan-idm.yml.j2
        dest: /root/idm-plan.yml
        mode: '0600'
    - name: Create idm plan
      command: kcli create plan -f /root/idm-plan.yml idm-plan
      no_log: true

- name: Deploy controllers VM plan
  when: "'controllers-plan' not in plan_check.stdout_lines"
  block:
    - name: Render controllers plan
      template:
        src: plan-controllers.yml.j2
        dest: /root/controllers-plan.yml
        mode: '0600'
    - name: Create controllers plan
      command: kcli create plan -f /root/controllers-plan.yml controllers-plan
      no_log: true

- name: Deploy compute VM plan
  when: "'compute-plan' not in plan_check.stdout_lines"
  block:
    - name: Render compute plan
      template:
        src: plan-compute.yml.j2
        dest: /root/compute-plan.yml
        mode: '0600'
    - name: Create compute plan
      command: kcli create plan -f /root/compute-plan.yml compute-plan
      no_log: true

- name: Get director VM IP address
  command: kcli list vm -P name=director -o json | jq -r '.[].ip // .[].ips[0]'
  register: director_ip_result
  changed_when: false
  retries: 12
  delay: 10
  until: >
    director_ip_result.stdout is defined and
    director_ip_result.stdout != "" and
    director_ip_result.stdout != "null" and
    director_ip_result.stdout is match("^[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}$")

- name: Append director IP and hostname to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ director_ip_result.stdout }} director"
    state: present
    backup: yes
  when: director_ip_result.stdout is match("^[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}$")

- name: Get idm VM IP address
  command: kcli list vm -P name=idm -o json | jq -r '.[].ip // .[].ips[0]'
  register: idm_ip_result
  changed_when: false
  retries: 12
  delay: 10
  until: >
    idm_ip_result.stdout is defined and
    idm_ip_result.stdout != "" and
    idm_ip_result.stdout != "null" and
    idm_ip_result.stdout is match("^[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}$")

- name: Append idm IP and hostname to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ idm_ip_result.stdout }} idm"
    state: present
    backup: yes
  when: idm_ip_result.stdout is match("^[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}$")