- name: Check if kcli plans already exist
  ansible.builtin.shell: kcli list plan -o name
  register: plan_check
  changed_when: false
  failed_when: false

- name: Deploy VM plans
  when: "plan_name not in plan_check.stdout_lines"
  include_tasks: vm_plans.yml
  loop_control:
    loop_var: plan_name
  loop:
    - director
    - idm
    - controllers
    - compute

- name: Start VMs and update /etc/hosts
  include_tasks: start_vms.yml
  loop:
    - director
    - idm
  loop_control:
    loop_var: vm_name